name: Generate Snake Animation

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual run
  push:
    branches:
      - main

jobs:
  build:
    name: Generate snake animation
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate snake SVG with custom colors
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: pryamflores
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=00FF00&color_dots=#2F4F4F,#006400,#2E8B57,#3CB371,#90EE90

      # Deploy the generated snake to the output branch
      - name: Push Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
